version: "3.8"

services:
    vcb-api-app:
        build: ./server/vcb-api/
        image: vcb-api-app
        container_name: vcb-api-app
        restart: unless-stopped
        ports:
            - 4000:9898
        depends_on:
            - vcb-api-db
    vcb-api-db:
        image: mariadb:10.7
        container_name: vcb-api-db
        restart: unless-stopped
        volumes:
            - ./server/vcb-api/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: vcb
            MYSQL_USER: root
            MYSQL_PASSWORD: matkhaumysql
            MYSQL_ROOT_PASSWORD: matkhaumysql
    momo-api-app:
        build: ./server/momo-api/
        image: momo-api-app
        container_name: momo-api-app
        restart: unless-stopped
        ports: 
            - "8091:80"
        volumes:
            - ./server/momo-api/src:/var/www/html/
        links:
            - momo-api-db
        networks:
            - default
    momo-api-db:
        image: mysql:8.0
        container_name: momo-api-db
        restart: unless-stopped
        ports: 
            - "3308:3308"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: momo
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./server/momo-api/dump/momo.sql:/docker-entrypoint-initdb.d/momo.sql
            # - ./conf:/etc/mysql/conf.d
            # - persistent:/var/lib/mysql
        networks:
            - default
    # momo-api-phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     container_name: momo-api-phpmyadmin
    #     links: 
    #         - momo-api-db:momo-api-db
    #     ports:
    #         - "${MOMO_PHPMYADMIN_PORT}:80"
    #     environment:
    #         MYSQL_USER: user
    #         MYSQL_PASSWORD: test
    #         MYSQL_ROOT_PASSWORD: test

# volumes:
#     persistent:
networks:
    frontend:
