name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/check-lsgd-vcb-momo/
          sudo git restore .
          sudo git pull https://github.com/hophamlam/check-lsgd-vcb-momo.git
          sudo docker-compose build
          sudo docker-compose up -d
          echo "hi!"
